### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by Joxit** [pelias/parser#59]
Hey team! 

There is an error with travis, some permissions are missing for this project `SemanticReleaseError: The push permission to the Git repository is required.`
https://travis-ci.org/pelias/parser/jobs/584546204

**Comment by missinglink** [comment]
There has been something weird going on with the Travis integration on those repo since the beginning.

I've actually emailed them twice about it but I think it's still broken.

I suspect the issue was that it was building on the travis-ci.com domain while I was developing it (remember it was private for a couple weeks in the beginning), now it's building on both .com and .org domains.

Here's the link to the .com build but you might not have permission to view it (it's passing).

https://travis-ci.com/pelias/parser

**Comment by missinglink** [comment]
Also I'm over Travis, Julian & I would like to move everything to Circle at some point, it's just so much faster and the UI is better.

**Comment by Joxit** [comment]
Oh yeah the .com is working, that means the project is registered on the travis.com and travis.org ? :thinking: 

So nothing to worry about then ? (I don't like the cross :x: on our commits :laughing: )

**Comment by Joxit** [comment]
There is still an issue with the CI, the last release was in 2019 :confused:

**Comment by missinglink** [comment]
Hmm yeah, I think the issue is with the secrets, they seem to be set on the dot com domain but not the dot org one.

@orangejulius do you know how to fix this?

I'm not sure how to remove it from the dot com but it appears to no longer be building there which is progress.

Maybe all that's required now is to add the secrets on dot org?

**Comment by orangejulius** [comment]
Okay, I updated the secrets on travis-ci.org, and removed them from travis-ci.com. The build now looks to be passing, so hopefully this is all good! If not, let me know.

**Comment by orangejulius** [comment]
https://github.com/pelias/parser/releases/tag/v1.45.0 Is the release that was just published by the way, it contains a lot!
