### ISSUE TITLE
US highway address

### ISSUE THREAD

**Issue by missinglink** [pelias/parser#60]
Worth checking if we support these:

```
1111 MD 760, Lusby, MD, USA
```

**Comment by Joxit** [comment]
What should be the correct parsing for this ? 

This one ? 

```json
[ { street: 'MD 760' },
  { housenumber: '1111' },
  { locality: 'Lusby' },
  { region: 'MD' },
  { country: 'USA' } ]
```

**Comment by orangejulius** [comment]
That's correct. Note that highways in the US can get a little complicated because there are different highway systems in every state.

The same road might be written as "state highway 760", "Maryland 760", etc.

In California there is "CA 1", "Route 1", "state highway 1", etc. It's probably more important when generating synonyms in Elasticsearch (which we don't do a great job of right now), but something to be aware of. Matching all the possible ways people enter names for these highways is hard.

**Comment by Joxit** [comment]
And I suppose that we can also write `MD-760` for example? Yes this will be a bit hard...

If we don't want to increase the number of synonyms in ES, we should normalise these names at import time as an alias name.
For example use `State Highway` every time  and when we will search and parse MD 760 as a street name, we could replace MD by street highway.

Using the alias will not alter the original data and we can detect the state with PIP.

**Comment by Joxit** [comment]
Sorry, Github auto closed this issue :sweat_smile:
