### ISSUE TITLE
Future management for WhosOnFirst dictionary

### ISSUE THREAD

**Issue by Joxit** [pelias/parser#9]
For now, only eng is supported. If we need to add support for other languages, I suggest doing a single file by type containing the list of sorted elements (one for regions, one for cities ....).

## Pros

- If we remove duplicates, this will save space (3MB for eng localities, this should be the same for other languages)
- A lot of localities are named with the local name in many languages (e.g [Paris](https://spelunker.whosonfirst.org/id/101751119/) have the same naming in eng, fra, deu and dozens of other languages) -> Save space & loading time
 - If we sort elements now in eng, when we will add a new language, the `git diff` will be smaller and more controlled -> Save repository space when `git clone` it

## Cons

- We can't remove/use one specific language with a configuration (for example use parser in a fra context only or a eng one...)
- Maybe we will exceed [github quota](https://help.github.com/en/articles/what-is-my-disk-quota) -> can be solved with one file by Latin letter ? or range letter (e.g `a-d.txt` `e-h.txt`....)

What do you think ?

**Comment by missinglink** [comment]
I'm not super worried about disk space, I think the only negatives for having duplicate data are:
- Increased repo size makes clones take a little longer
- Increased parser start times parsing duplicate lines

But I think that those aren't really that bad, and the positives are like you mentioned, that we have more flexibility in which files we load and which ones we don't.

The really important thing is that they are not duplicated in RAM, which would be really bad.

Honestly, we don't know yet what will be best, maybe we do this in the future once the repo is battle-tested and we know better how we want to use it.

For now, since it's still a young project, I would prefer to err on the side of flexibility at the cost of correctness rather than the other way around, if that makes sense?

**Comment by missinglink** [comment]
One other thing I've been considering is 'classification metadata', which is currently supported but not used.
This could be interesting because it would allow us to do things like ensuring that French names go with French prefixes and French localities, or at least scoring those things higher in the results.

In order to achieve that we'd need to keep the tokens separate so that we could classify in different ways.

Just a thought..

**Comment by missinglink** [comment]
ref: https://github.com/pelias/parser/blob/master/classification/Classification.js#L6

**Comment by missinglink** [comment]
Closing for now, happy to revisit this issue in the future once we have more experience working with the parser.
